apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
data:
  hive-site.xml: |
    {{ .Values.hiveSiteXml | nindent 4 }}
